# Etapa de construcción
FROM node:22-alpine as builder

WORKDIR /app
COPY package.json package-lock.json ./  
RUN npm ci  
COPY . .  
RUN npm run build  

FROM nginx:alpine  
COPY --from=builder /app/dist /usr/share/nginx/html/MundoAnime  
COPY nginx.conf /etc/nginx/conf.d/default.conf  
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]  